export const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TRIP_NOT_FOUND: 'TRIP_NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // 行程与成员
  NOT_TRIP_MEMBER: 'NOT_TRIP_MEMBER',

  // 预算
  BUDGET_CATEGORY_EMPTY: 'BUDGET_CATEGORY_EMPTY',
  BUDGET_AMOUNT_INVALID: 'BUDGET_AMOUNT_INVALID',

  // 支出登记
  EXPENSE_TRIP_REQUIRED: 'EXPENSE_TRIP_REQUIRED',
  EXPENSE_RECEIPT_EMPTY: 'EXPENSE_RECEIPT_EMPTY',
  EXPENSE_TITLE_EMPTY: 'EXPENSE_TITLE_EMPTY',
  EXPENSE_AMOUNT_INVALID: 'EXPENSE_AMOUNT_INVALID',
  EXPENSE_CATEGORY_EMPTY: 'EXPENSE_CATEGORY_EMPTY',
  RECEIPT_DUPLICATED: 'RECEIPT_DUPLICATED',
  EXPENSE_NOT_FOUND: 'EXPENSE_NOT_FOUND',
  CANNOT_CONFIRM_OWN: 'CANNOT_CONFIRM_OWN',
  EXPENSE_NOT_PENDING: 'EXPENSE_NOT_PENDING',
  NOT_EXPENSE_OWNER: 'NOT_EXPENSE_OWNER',
  EXPENSE_NOT_REJECTED: 'EXPENSE_NOT_REJECTED',
  TRIP_ALREADY_SETTLED: 'TRIP_ALREADY_SETTLED',
  EXPENSES_PENDING: 'EXPENSES_PENDING',
  EXPENSES_REJECTED: 'EXPENSES_REJECTED',
  NO_TRIP_MEMBERS: 'NO_TRIP_MEMBERS',
  SETTLEMENT_IN_PROGRESS: 'SETTLEMENT_IN_PROGRESS'
} as const;
