export const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  TRIP_NOT_FOUND: 'TRIP_NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_TRIP_MEMBER: 'NOT_TRIP_MEMBER',
  EXPENSE_NOT_FOUND: 'EXPENSE_NOT_FOUND',
  RECEIPT_DUPLICATED: 'RECEIPT_DUPLICATED',
  SELF_CONFIRM_NOT_ALLOWED: 'SELF_CONFIRM_NOT_ALLOWED',
  EXPENSE_ALREADY_PROCESSED: 'EXPENSE_ALREADY_PROCESSED',
  EXPENSES_UNRESOLVED: 'EXPENSES_UNRESOLVED',
  SETTLEMENT_EXISTS: 'SETTLEMENT_EXISTS',
  SETTLEMENT_NOT_FOUND: 'SETTLEMENT_NOT_FOUND'
} as const;
